FROM alpine:3.22

LABEL maintainer="contact@omnilium.com"
LABEL description="Lightweight toolbox image with various commonly used tools."

RUN apk add --no-cache \
    bash \
    curl \
    ncftp \
    unzip \
    zip

ENTRYPOINT [ "bash" ]
