when:
- event: push
  branch: main

matrix:
  IMAGE:
  - toolbox

steps:
- name: build
  image: woodpeckerci/plugin-kaniko:latest
  when:
  - path: ${IMAGE}/*
  settings:
    dry-run: true
    registry: git.omni.ms
    repo: omnilium/${IMAGE}
    username:
      from_secret: podman_registry_username
    password:
      from_secret: podman_registry_password
    dockerfile: ${IMAGE}/Dockerfile
    tags: latest
