when:
- event: push
  branch: main

matrix:
  IMAGE:
  - toolbox

steps:
- name: publish
  image: woodpeckerci/plugin-kaniko:latest
  settings:
    registry: https://git.omni.ms
    repo: omnilium/${IMAGE}
    username:
      from_secret: podman_registry_username
    password:
      from_secret: podman_registry_password
    dockerfile: ${IMAGE}/Dockerfile
    tags: latest
