when:
  - event: tag

matrix:
  IMAGE:
    - node
    - toolbox

steps:
  - name: publish
    image: woodpeckerci/plugin-kaniko:latest
    pull: true
    when:
      - evaluate: 'CI_COMMIT_TAG contains IMAGE'
    settings:
      dry-run: false
      registry: git.omni.ms
      repo: omnilium/${IMAGE}
      username:
        from_secret: podman_registry_username
      password:
        from_secret: podman_registry_password
      dockerfile: ${IMAGE}/Dockerfile
      tags:
        - latest
        - ${CI_COMMIT_TAG:0:5}

  - name: release
    image: woodpeckerci/plugin-release:latest
    pull: true
    when:
      - evaluate: 'CI_COMMIT_TAG contains IMAGE'
    settings:
      api-key:
        from_secret: forgejo_release_key
      draft: true
