when:
- event: tag

matrix:
  IMAGE:
  - toolbox

steps:
- name: build
  image: woodpeckerci/plugin-kaniko:latest
  settings:
    dry-run: false
    registry: https://git.omni.ms
    repo: omnilium/${IMAGE}
    username:
      from_secret: podman_registry_username
    password:
      from_secret: podman_registry_password
    dockerfile: ${IMAGE}/Dockerfile
    tags: latest
